# Auto-generated by orchestrate. Edit with care.
META = {'app_id': 'gaotu', 'bundle_id': 'com.gaotu100.superclass', 'app_version': '', 'record_id': 'recvrdu2RpMvvP', 'name': '上课tab进入缓存课程页面并返回验证', 'module': '上课', 'platform': 'android', 'generated_at': '2026-08-04 09:38:52'}
FLOW = [{'type': 'prepare_state', 'target': 'class_tab', 'account': '12345679000'}, {'type': 'tap', 'by': 'coord', 'value': '(1880,115) 顶栏最右more按钮bounds[1842,68][1918,162]'}, {'type': 'tap', 'by': 'text', 'value': "缓存课程 (菜单项clickable容器bounds[1633,184][1897,269],text=' 缓存课程')"}, {'type': 'back', 'by': 'id', 'value': 'com.gaotu100.superclass:id/headbar_left_btn'}]


def execute(ctx):
    return ctx["run_flow"](META, FLOW)
