# Auto-generated by orchestrate. Edit with care.
META = {'app_id': 'gaotu', 'bundle_id': 'com.gaotu100.superclass', 'app_version': '', 'record_id': 'recvpZkE1oKsKA', 'name': 'android登录-微信登录(已绑定手机号)', 'module': '登录', 'platform': 'android', 'generated_at': '2026-07-31 17:25:56'}
FLOW = [{'type': 'tap', 'by': 'text', 'value': 'text=立即登录~'}, {'type': 'tap', 'by': 'text', 'value': 'id=wechat_sign_in_iv'}, {'type': 'tap', 'by': 'text', 'value': 'id=customer_dialog_ok'}]


def execute(ctx):
    return ctx["run_flow"](META, FLOW)
