# Auto-generated by orchestrate. Edit with care.
META = {'app_id': 'gaotu', 'bundle_id': 'com.gaotu100.superclass', 'app_version': '', 'record_id': 'recvrdu2Rpw709', 'name': '班级卡片样式-1v1点击进课节列表', 'module': '上课', 'platform': 'android', 'generated_at': '2026-08-03 17:01:26'}
FLOW = [{'type': 'prepare_state', 'target': 'class_tab', 'account': '12345679000'}, {'type': 'assert_text', 'value': 'text命中: 中国文学素养；B素养-平台化回归-1v1B；共50课时·未学习；技术(主讲；石金鸽(二讲', 'text': '1.品类/科目、班级名称、共x课时、主讲/二讲老师头像和名称展示正常'}, {'type': 'assert_ui', 'text': 'UI规范检查：1.品类/科目、班级名称、共x课时、主讲/二讲老师头像和名称展示正常', 'scope': 'current_screen', 'rules': ['no_blank', 'no_overlap', 'no_occlusion', 'no_truncation', 'safe_area']}, {'type': 'tap', 'by': 'xpath', 'value': "//*[contains(@text,'B素养-平台化回归-1v1B')]"}, {'type': 'assert_id', 'value': "//*[contains(@text,'课程目录')] 命中,课节列表(1.小明-石金鸽 2.给劲儿)展示", 'text': '2.点击后成功进入课节列表页'}, {'type': 'assert_ui', 'text': 'UI规范检查：2.点击后成功进入课节列表页', 'scope': 'current_screen', 'rules': ['no_blank', 'no_overlap', 'no_occlusion', 'no_truncation', 'safe_area']}, {'type': 'assert_id', 'value': "//*[@text='今日学习推荐' or @text='我的课程'] 命中", 'text': '3.返回到上课tab'}, {'type': 'assert_ui', 'text': 'UI规范检查：3.返回到上课tab', 'scope': 'current_screen', 'rules': ['no_blank', 'no_overlap', 'no_occlusion', 'no_truncation', 'safe_area']}]


def execute(ctx):
    return ctx["run_flow"](META, FLOW)
