# Auto-generated by orchestrate. Edit with care.
META = {'app_id': 'gaotu', 'bundle_id': 'com.gaotu100.superclass', 'app_version': '', 'record_id': 'recvrdu2RpAsEA', 'name': '班级卡片样式-预约1v1点击进预约h5', 'module': '上课', 'platform': 'android', 'generated_at': '2026-08-03 17:01:26'}
FLOW = [{'type': 'prepare_state', 'target': 'class_tab', 'account': '12345679000'}, {'type': 'assert_text', 'value': 'text命中: 心理咨询服务；B1v1课程B；共100次；已预约0次·剩余100次；高途老师(主讲头像', 'text': '1. 品类、科目、班级名称、共x次、已预约x次·剩余y次、主讲老师头像名称展示正常'}, {'type': 'assert_ui', 'text': 'UI规范检查：1. 品类、科目、班级名称、共x次、已预约x次·剩余y次、主讲老师头像名称展示正常', 'scope': 'current_screen', 'rules': ['no_blank', 'no_overlap', 'no_occlusion', 'no_truncation', 'safe_area']}, {'type': 'tap', 'by': 'xpath', 'value': "//*[contains(@text,'B1v1课程B')]"}, {'type': 'assert_id', 'value': "//*[@text='今日学习推荐' or @text='我的课程'] 命中", 'text': '3. 返回上课tab'}, {'type': 'assert_ui', 'text': 'UI规范检查：3. 返回上课tab', 'scope': 'current_screen', 'rules': ['no_blank', 'no_overlap', 'no_occlusion', 'no_truncation', 'safe_area']}]


def execute(ctx):
    return ctx["run_flow"](META, FLOW)
