# Auto-generated by orchestrate. Edit with care.
META = {'app_id': 'gaotu', 'bundle_id': 'com.gaotu100.superclass', 'app_version': '', 'record_id': 'recvrdu2RpeOJr', 'name': '班级卡片样式-大班课点击进课节列表', 'module': '上课', 'platform': 'android', 'generated_at': '2026-08-03 17:01:26'}
FLOW = [{'type': 'prepare_state', 'target': 'class_tab', 'account': '12345679000'}, {'type': 'assert_text', 'value': '卡片text命中: 物理(品类；科目；B教学线上走查大班-aB(班级名称；共3节(共x节；已学1节(开课；进度信息；该课已开课故显示学习进度而非下次课时间；石金鸽(主讲)+王金峰03(二讲)含头像', 'text': '1.品类、科目、班级名称、共x节、开课信息、主讲/二讲老师头像和名称展示正常'}, {'type': 'assert_ui', 'text': 'UI规范检查：1.品类、科目、班级名称、共x节、开课信息、主讲/二讲老师头像和名称展示正常', 'scope': 'current_screen', 'rules': ['no_blank', 'no_overlap', 'no_occlusion', 'no_truncation', 'safe_area']}, {'type': 'tap', 'by': 'xpath', 'value': "//*[contains(@text,'B教学线上走查大班-aB')]"}, {'type': 'assert_id', 'value': "//*[contains(@text,'课程目录')] 命中;详情页标题B教学线上走查大班-aB,听课进度33%,课节列表(赠课0423/0527回归/B教学走查大班考试B/B考试报告B等)展示", 'text': '2.点击后成功进入课节列表页'}, {'type': 'assert_ui', 'text': 'UI规范检查：2.点击后成功进入课节列表页', 'scope': 'current_screen', 'rules': ['no_blank', 'no_overlap', 'no_occlusion', 'no_truncation', 'safe_area']}]


def execute(ctx):
    return ctx["run_flow"](META, FLOW)
