# Auto-generated by orchestrate. Edit with care.
META = {'app_id': 'gaotu', 'bundle_id': 'com.gaotu100.superclass', 'app_version': '', 'record_id': 'recvrdu2RpZ4Dv', 'name': '上课tab页面点击错题本及返回功能验证', 'module': '上课', 'platform': 'android', 'generated_at': '2026-08-03 16:41:59'}
FLOW = [{'type': 'prepare_state', 'target': 'class_tab', 'account': '12345679000'}, {'type': 'tap', 'by': 'text', 'value': '错题本'}, {'type': 'tap', 'by': 'coord', 'value': '44,114', 'fallbacks': [{'by': 'ai', 'value': 'back arrow at top-left of 错题本 page'}]}, {'type': 'assert_text', 'value': "*[@text='我的课程'] 与；*[@text='错题本'] 均命中(上课tab签名", 'text': '2.返回到上课tab'}, {'type': 'assert_ui', 'text': 'UI规范检查：2.返回到上课tab', 'scope': 'current_screen', 'rules': ['no_blank', 'no_overlap', 'no_occlusion', 'no_truncation', 'safe_area']}]


def execute(ctx):
    return ctx["run_flow"](META, FLOW)
