# Auto-generated by orchestrate. Edit with care.
META = {'app_id': 'gaotu', 'bundle_id': 'com.gaotu100.superclass', 'app_version': '', 'record_id': 'recvrdu2RpCGRB', 'name': 'AI闪学课程班级左右滑动切换验证', 'module': 'AI闪学', 'platform': 'android', 'generated_at': '2026-08-03 19:18:03'}
FLOW = [{'type': 'tap', 'by': 'text', 'value': 'coordinate(1018,1549)'}, {'type': 'swipe', 'by': 'text', 'value': 'coordinate(1820,492)->(760,492)'}, {'type': 'swipe', 'by': 'text', 'value': 'coordinate(760,492)->(1820,492)'}]


def execute(ctx):
    return ctx["run_flow"](META, FLOW)
