# Auto-generated by orchestrate. Edit with care.
META = {'app_id': 'gaotu', 'bundle_id': 'com.gaotu100.superclass', 'app_version': '', 'record_id': 'recvrdu2RpAruT', 'name': '课节详情页看视频', 'module': '上课', 'platform': 'android', 'generated_at': '2026-08-03 18:13:43'}
FLOW = [{'type': 'prepare_state', 'target': 'class_tab', 'account': '12345679000'}, {'type': 'tap', 'by': 'coord', 'value': '(640,640)'}, {'type': 'tap', 'by': 'text', 'value': '看视频 (bounds[1385,1131][1469,1174] 中心1427,1152)'}, {'type': 'back', 'by': 'system', 'value': 'BACK'}, {'type': 'tap', 'by': 'xpath', 'value': "//*[@text='确定']"}, {'type': 'tap', 'by': 'coord', 'value': "(1877,1010) 课节'1. 测试'标题行(避开看视频按钮)"}, {'type': 'tap', 'by': 'text', 'value': '去看课 (bounds[2374,508][2458,551] 中心2416,529)'}, {'type': 'back', 'by': 'system', 'value': 'BACK'}, {'type': 'tap', 'by': 'xpath', 'value': "//*[@text='确定']"}, {'type': 'back', 'by': 'system', 'value': 'BACK'}]


def execute(ctx):
    return ctx["run_flow"](META, FLOW)
