# Auto-generated by orchestrate. Edit with care.
META = {'app_id': 'gaotu', 'bundle_id': 'com.gaotu100.superclass', 'app_version': '', 'record_id': 'recvrdu2RpdqpU', 'name': 'AI闪学课程详情页功能验证用例', 'module': 'AI闪学', 'platform': 'android', 'generated_at': '2026-08-03 19:18:03'}
FLOW = [{'type': 'swipe+tap', 'by': 'text', 'value': 'swipe(1820,492)->(760,492); tap card(1568,384)'}, {'type': 'tap', 'by': 'text', 'value': 'pill(2450,115)'}, {'type': 'tap', 'by': 'text', 'value': 'text 添加老师(1826,442)'}, {'type': 'tap', 'by': 'text', 'value': 'text 查看说明(2278,442)'}, {'type': 'tap', 'by': 'id', 'value': 'id com.gaotu100.superclass:id/video_back'}]


def execute(ctx):
    return ctx["run_flow"](META, FLOW)
