# Auto-generated by orchestrate. Edit with care.
META = {'app_id': 'gaotu', 'bundle_id': 'com.gaotu100.superclass', 'app_version': '', 'record_id': 'recvpYuUxb74CV', 'name': 'android登录-微信登录(未绑定手机号)', 'module': '登录', 'platform': 'android', 'generated_at': '2026-07-31 17:25:56'}
FLOW = [{'type': 'tap', 'by': 'text', 'value': 'id=点击登录'}, {'type': 'tap', 'by': 'text', 'value': 'id=wechat_sign_in_iv'}, {'type': 'tap', 'by': 'text', 'value': 'id=customer_dialog_ok'}, {'type': 'set_value', 'by': 'text', 'value': 'id=account_enter_et', 'text': '12100000001'}, {'type': 'tap', 'by': 'text', 'value': 'id=seccurity_detection_next_step'}, {'type': 'set_value', 'by': 'text', 'value': 'id=verify_code_edit_text', 'text': '1000'}, {'type': 'tap', 'by': 'text', 'value': 'text=退出登录 -> 确定'}]


def execute(ctx):
    return ctx["run_flow"](META, FLOW)
