# 每个 app 可覆盖，留空则继承 default
default:
  android:
    - udid: "26KUT24202013751"
      name: "华为 ADA-AL00"
    - udid: "cd5c614a"
      name: "小米 23127PN0CC (houji)"
  ios:
    - udid: "00008101-001E28D436E0001E"
      name: "111的iPhone12 (iOS 18.7.8)"
    - udid: "00008110-00180CD9348B801E"
      name: "iPhone (iOS 18.7.8)"
