# Auto-generated by orchestrate. Edit with care.
META = {'app_id': 'gaotu', 'bundle_id': 'com.gaotu100.superclass', 'app_version': '5.92.10', 'record_id': 'recvpYuU3AcYi4', 'name': '登录-密码登录', 'module': '启动登录', 'platform': 'ios', 'generated_at': '2026-07-30 11:28:33'}
FLOW = [{'type': 'tap', 'by': 'accessibility id', 'value': '点击登录 欢迎来到高途', 'fallbacks': [{'by': 'coordinate', 'value': '(86,97)'}]}, {'type': 'tap', 'by': 'accessibility id', 'value': '密码登录'}, {'type': 'set_value', 'by': 'accessibility id', 'value': '请输入手机号(TextField)', 'text': '12345679000'}, {'type': 'set_value', 'by': 'accessibility id', 'value': '请输入密码(SecureTextField)', 'text': 'Gaotu@123'}, {'type': 'tap', 'by': 'accessibility id', 'value': 'icon showPassword'}, {'type': 'tap', 'by': 'accessibility id', 'value': '登录'}, {'type': 'tap', 'by': 'accessibility id', 'value': '退出登录'}]


def execute(ctx):
    return ctx["run_flow"](META, FLOW)
