# Auto-generated by orchestrate. Edit with care.
META = {'app_id': 'gaotu', 'bundle_id': 'com.gaotu100.superclass', 'app_version': '5.91.92', 'record_id': 'recvpZKcASbq6e', 'name': 'Tab导航-默认选中与切换', 'module': '启动登录', 'platform': 'ios', 'generated_at': '2026-07-28 13:38:41'}
FLOW = [{'type': 'prepare_state', 'target': 'home', 'account': '12345679000'}, {'type': 'assert_id', 'value': 'by=name,value=首页 命中且底部首页tab红色高亮选中', 'text': '1. 默认选中首页 Tab'}, {'type': 'assert_ui', 'text': 'UI规范检查：1. 默认选中首页 Tab', 'scope': 'current_screen', 'rules': ['no_blank', 'no_overlap', 'no_occlusion', 'no_truncation', 'safe_area']}, {'type': 'tap', 'by': 'name', 'value': '圈子', 'fallbacks': [{'by': 'xpath', 'value': "//*[@name='圈子']"}]}, {'type': 'tap', 'by': 'name', 'value': '发现', 'fallbacks': [{'by': 'xpath', 'value': "//*[@name='发现']"}]}]


def execute(ctx):
    return ctx["run_flow"](META, FLOW)
