# Auto-generated by orchestrate. Edit with care.
META = {'app_id': 'gaotu', 'bundle_id': 'com.gaotu100.superclass', 'app_version': '5.92.10', 'record_id': 'recvpZKcASbq6e', 'name': 'Tab导航-默认选中与切换', 'module': '启动登录', 'platform': 'ios', 'generated_at': '2026-07-30 12:51:33'}
FLOW = [{'type': 'prepare_state', 'target': 'home', 'account': '12345679000'}, {'type': 'assert_id', 'value': "name='首页' traits='Button, Selected' (底部标签页栏)", 'text': '1. 默认选中首页 Tab'}, {'type': 'assert_ui', 'text': 'UI规范检查：1. 默认选中首页 Tab', 'scope': 'current_screen', 'rules': ['no_blank', 'no_overlap', 'no_occlusion', 'no_truncation', 'safe_area']}, {'type': 'tap', 'by': 'name', 'value': '放弃讲义', 'fallbacks': [{'by': 'label', 'value': '放弃讲义'}]}, {'type': 'tap', 'by': 'name', 'value': '圈子', 'fallbacks': [{'by': 'label', 'value': '圈子'}]}, {'type': 'tap', 'by': 'name', 'value': '发现', 'fallbacks': [{'by': 'label', 'value': '发现'}]}, {'type': 'assert_text', 'value': "appium_find_element name='今日推荐' 命中 + 发现子tab加粗红下划线选中", 'text': '4. 发现 Tab 内容正常展示'}, {'type': 'assert_ui', 'text': 'UI规范检查：4. 发现 Tab 内容正常展示', 'scope': 'current_screen', 'rules': ['no_blank', 'no_overlap', 'no_occlusion', 'no_truncation', 'safe_area']}]


def execute(ctx):
    return ctx["run_flow"](META, FLOW)
