# Auto-generated by orchestrate. Edit with care.
META = {'app_id': 'gaotu', 'bundle_id': 'com.gaotu100.superclass', 'app_version': '5.91.92', 'record_id': 'recvpZKcASbq6e', 'name': 'Tab导航-默认选中与切换', 'module': '启动登录', 'platform': 'ios', 'generated_at': '2026-07-29 12:09:14'}
FLOW = [{'type': 'prepare_state', 'target': 'home', 'account': '12345679000'}, {'type': 'activate', 'by': 'accessibility_id', 'value': 'com.gaotu100.superclass'}, {'type': 'tap', 'by': 'accessibility_id', 'value': '圈子', 'fallbacks': [{'by': 'xpath', 'value': "//XCUIElementTypeButton[@name='圈子']"}]}, {'type': 'tap', 'by': 'accessibility_id', 'value': '发现', 'fallbacks': [{'by': 'xpath', 'value': "//XCUIElementTypeButton[@name='发现']"}]}]


def execute(ctx):
    return ctx["run_flow"](META, FLOW)
