# Auto-generated by orchestrate. Edit with care.
META = {'app_id': 'gaotu', 'bundle_id': 'com.gaotu100.superclass', 'app_version': '', 'record_id': 'recvpZKbjhCHXl', 'name': '我的Tab-设置-退出登录功能验证', 'module': '我的', 'platform': 'ios', 'generated_at': '2026-07-31 17:50:19'}
FLOW = [{'type': 'prepare_state', 'account': '12345679000'}, {'type': 'tap', 'by': 'accessibility_id', 'value': 'coordinate(372,69) 右上角最右图标', 'fallbacks': [{'by': 'accessibility_id', 'value': 'ai:hexagon settings icon rightmost top-right of 我的 page'}]}, {'type': 'tap', 'by': 'accessibility_id', 'value': '退出登录'}, {'type': 'tap', 'by': 'accessibility_id', 'value': '确定'}]


def execute(ctx):
    return ctx["run_flow"](META, FLOW)
