# Auto-generated by orchestrate. Edit with care.
META = {'app_id': 'gaotu', 'bundle_id': 'com.gaotu100.superclass', 'app_version': '', 'record_id': 'recvpYuTNMt9O6', 'name': '验证码登录流程测试', 'module': '启动登录', 'platform': 'ios', 'generated_at': '2026-07-31 17:40:47'}
FLOW = [{'type': 'prepare_state', 'target': 'login', 'account': '<UNLOGIN>'}, {'type': 'input', 'by': 'predicate', 'value': "type=='XCUIElementTypeTextField'", 'text': '12345679000'}, {'type': 'tap', 'by': 'accessibility_id', 'value': '获取验证码'}, {'type': 'tap', 'by': 'accessibility_id', 'value': '同意'}, {'type': 'input', 'by': 'accessibility_id', 'value': '四位方形验证码框(键盘输入)', 'text': '1000'}, {'type': 'tap', 'by': 'xpath', 'value': "//*[@name='我的']"}]


def execute(ctx):
    return ctx["run_flow"](META, FLOW)
