# Auto-generated by orchestrate. Edit with care.
META = {'app_id': 'gaotu', 'bundle_id': 'com.gaotu100.superclass', 'app_version': '', 'record_id': 'recvpYuU3AcYi4', 'name': 'recvpYuU3AcYi4 登录-密码登录', 'module': '登录', 'platform': 'ios', 'generated_at': '2026-07-31 17:40:47'}
FLOW = [{'type': 'assert_id', 'value': 'accessibility id=密码登录标题 + 请输入密码输入框存在'}, {'type': 'assert_ui', 'text': 'UI规范检查', 'scope': 'current_screen', 'rules': ['no_blank', 'no_overlap', 'no_occlusion', 'no_truncation', 'safe_area']}, {'type': 'assert_text', 'value': '手机号字段显示 123****9000'}, {'type': 'assert_ui', 'text': 'UI规范检查', 'scope': 'current_screen', 'rules': ['no_blank', 'no_overlap', 'no_occlusion', 'no_truncation', 'safe_area']}, {'type': 'w3c set_value', 'by': 'accessibility_id', 'value': 'coord(100,238) focus', 'text': 'Gaotu@123'}, {'type': 'assert_text', 'value': '密码字段明文显示 Gaotu@123 (screenshot c2_pwd_plaintext.png'}, {'type': 'assert_ui', 'text': 'UI规范检查', 'scope': 'current_screen', 'rules': ['no_blank', 'no_overlap', 'no_occlusion', 'no_truncation', 'safe_area']}, {'type': 'assert_id', 'value': 'accessibility id=小九 命中 + 手机号 123****9000 (screenshot c2_login_success.png)'}, {'type': 'assert_ui', 'text': 'UI规范检查', 'scope': 'current_screen', 'rules': ['no_blank', 'no_overlap', 'no_occlusion', 'no_truncation', 'safe_area']}]


def execute(ctx):
    return ctx["run_flow"](META, FLOW)
