# Auto-generated by orchestrate. Edit with care.
META = {'app_id': 'gaotu', 'bundle_id': 'com.gaotu100.superclass', 'app_version': '5.91.92', 'record_id': 'recvpZKcASpA9O', 'name': '未登录-上课tab点击登录注册按钮跳转登录页', 'module': '上课', 'platform': 'ios', 'generated_at': '2026-07-28 13:32:35'}
FLOW = [{'type': 'prepare_state', 'target': 'home', 'account': '<UNLOGIN>'}, {'type': 'tap', 'by': 'name', 'value': '上课', 'fallbacks': [{'by': 'xpath', 'value': "//*[@name='上课']"}]}, {'type': 'tap', 'by': 'coordinate', 'value': '363,73'}, {'type': 'tap', 'by': 'name', 'value': '登录/注册'}, {'type': 'input', 'by': 'class name', 'value': 'XCUIElementTypeTextField', 'text': '12345679000'}, {'type': 'tap', 'by': 'name', 'value': '获取验证码'}, {'type': 'tap', 'by': 'name', 'value': '同意'}, {'type': 'tap', 'by': 'coordinate', 'value': '58,232'}, {'type': 'input', 'by': 'accessibility_id', 'value': 'focused element (w3cActions)', 'text': '1000'}, {'type': 'tap', 'by': 'coordinate', 'value': '194,740'}]


def execute(ctx):
    return ctx["run_flow"](META, FLOW)
